---
- hosts: localhost
  connection: local

  tasks:
  - name: Create EC2 instances
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "devops-demo-1"
      instance_type: t2.micro
      security_group: default
      region: ap-south-1
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"      
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
      tags:
        environment: "{{ item.name }}"
    loop:
      - { image: "ami-04a37924ffe27da53", name: "manage-node-1" }
      - { image: "ami-0dee22c13ea7a9a67", name: "manage-node-2" }
      - { image: "ami-0dee22c13ea7a9a67", name: "manage-node-3" }
